# Generated by Django 5.0.7 on 2024-07-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_item_created_at_remove_item_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='preço',
        ),
    ]
